/* Automatically generated by wasm2c */
#ifndef CHUNKY_H_GENERATED_
#define CHUNKY_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_0x5F__wbindgen__placeholder__0x5F;

typedef struct w2c_chunky {
  struct w2c_0x5F__wbindgen__placeholder__0x5F* w2c_0x5F__wbindgen__placeholder__0x5F_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_chunky;

void wasm2c_chunky_instantiate(w2c_chunky*, struct w2c_0x5F__wbindgen__placeholder__0x5F*);
void wasm2c_chunky_free(w2c_chunky*);
wasm_rt_func_type_t wasm2c_chunky_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: '__wbindgen_placeholder__' '__wbindgen_json_parse' */
u32 w2c_0x5F__wbindgen__placeholder__0x5F_0x5F_wbindgen_json_parse(struct w2c_0x5F__wbindgen__placeholder__0x5F*, u32, u32);

/* import: '__wbindgen_placeholder__' '__wbindgen_throw' */
void w2c_0x5F__wbindgen__placeholder__0x5F_0x5F_wbindgen_throw(struct w2c_0x5F__wbindgen__placeholder__0x5F*, u32, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_chunky_memory(w2c_chunky* instance);

/* export: '__wbg_multinoisebiomesource_free' */
void w2c_chunky_0x5F_wbg_multinoisebiomesource_free(w2c_chunky*, u32);

/* export: 'multinoisebiomesource_new' */
u32 w2c_chunky_multinoisebiomesource_new(w2c_chunky*, u32);

/* export: 'multinoisebiomesource_get_noise_biome' */
u32 w2c_chunky_multinoisebiomesource_get_noise_biome(w2c_chunky*, u32, u32, u32, u32);

/* export: 'multinoisebiomesource_get_noise_biome_at_height_type' */
u32 w2c_chunky_multinoisebiomesource_get_noise_biome_at_height_type(w2c_chunky*, u32, u32, u32, u32);

/* export: 'multinoisebiomesource_get_approx_surface' */
u32 w2c_chunky_multinoisebiomesource_get_approx_surface(w2c_chunky*, u32, u32, u32, u32);

/* export: 'multinoisebiomesource_get_approx_surface_area' */
void w2c_chunky_multinoisebiomesource_get_approx_surface_area(w2c_chunky*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'multinoisebiomesource_get_noise_biome_area' */
void w2c_chunky_multinoisebiomesource_get_noise_biome_area(w2c_chunky*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'multinoisebiomesource_get_noise_biome_area_at_height_type' */
void w2c_chunky_multinoisebiomesource_get_noise_biome_area_at_height_type(w2c_chunky*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'multinoisebiomesource_find_spawn_position' */
void w2c_chunky_multinoisebiomesource_find_spawn_position(w2c_chunky*, u32, u32);

/* export: 'multinoisebiomesource_get_preliminary_surface_level' */
u32 w2c_chunky_multinoisebiomesource_get_preliminary_surface_level(w2c_chunky*, u32, u32, u32);

/* export: '__wbg_biomeprovider_free' */
void w2c_chunky_0x5F_wbg_biomeprovider_free(w2c_chunky*, u32);

/* export: 'biomeprovider_new' */
u32 w2c_chunky_biomeprovider_new(w2c_chunky*, u32);

/* export: 'biomeprovider_get_ints0' */
void w2c_chunky_biomeprovider_get_ints0(w2c_chunky*, u32, u32, u32, u32, u32, u32);

/* export: 'biomeprovider_get_ints1' */
void w2c_chunky_biomeprovider_get_ints1(w2c_chunky*, u32, u32, u32, u32, u32, u32);

/* export: '__wbg_world_free' */
void w2c_chunky_0x5F_wbg_world_free(w2c_chunky*, u32);

/* export: '__wbg_get_world_edition' */
u32 w2c_chunky_0x5F_wbg_get_world_edition(w2c_chunky*, u32);

/* export: '__wbg_set_world_edition' */
void w2c_chunky_0x5F_wbg_set_world_edition(w2c_chunky*, u32, u32);

/* export: '__wbg_get_world_version' */
u32 w2c_chunky_0x5F_wbg_get_world_version(w2c_chunky*, u32);

/* export: '__wbg_set_world_version' */
void w2c_chunky_0x5F_wbg_set_world_version(w2c_chunky*, u32, u32);

/* export: '__wbg_get_world_biome_size' */
void w2c_chunky_0x5F_wbg_get_world_biome_size(w2c_chunky*, u32, u32);

/* export: '__wbg_set_world_biome_size' */
void w2c_chunky_0x5F_wbg_set_world_biome_size(w2c_chunky*, u32, u32, u32);

/* export: '__wbg_get_world_large_biomes' */
u32 w2c_chunky_0x5F_wbg_get_world_large_biomes(w2c_chunky*, u32);

/* export: '__wbg_set_world_large_biomes' */
void w2c_chunky_0x5F_wbg_set_world_large_biomes(w2c_chunky*, u32, u32);

/* export: 'world_new' */
u32 w2c_chunky_world_new(w2c_chunky*, u32, u32, u32, u32, u32, u32, u32);

/* export: '__wbg_dungeonfinder_free' */
void w2c_chunky_0x5F_wbg_dungeonfinder_free(w2c_chunky*, u32);

/* export: 'dungeonfinder_new' */
u32 w2c_chunky_dungeonfinder_new(w2c_chunky*, u32);

/* export: 'dungeonfinder_find' */
u32 w2c_chunky_dungeonfinder_find(w2c_chunky*, u32, u32, u32, u32, u32);

/* export: '__wbg_oreveinfinder_free' */
void w2c_chunky_0x5F_wbg_oreveinfinder_free(w2c_chunky*, u32);

/* export: 'oreveinfinder_new' */
u32 w2c_chunky_oreveinfinder_new(w2c_chunky*, u32);

/* export: 'oreveinfinder_find' */
u32 w2c_chunky_oreveinfinder_find(w2c_chunky*, u32, u32, u32, u32, u32);

/* export: '__wbg_chunkgeneratorend_free' */
void w2c_chunky_0x5F_wbg_chunkgeneratorend_free(w2c_chunky*, u32);

/* export: 'chunkgeneratorend_new' */
u32 w2c_chunky_chunkgeneratorend_new(w2c_chunky*, u32);

/* export: 'chunkgeneratorend_build_height_map' */
void w2c_chunky_chunkgeneratorend_build_height_map(w2c_chunky*, u32, u32, u32, u32);

/* export: '__wbg_xoroshirorandomworldgen_free' */
void w2c_chunky_0x5F_wbg_xoroshirorandomworldgen_free(w2c_chunky*, u32);

/* export: 'xoroshirorandomworldgen_new' */
u32 w2c_chunky_xoroshirorandomworldgen_new(w2c_chunky*, u32, u32, u32, u32);

/* export: 'xoroshirorandomworldgen_new_from_seed' */
u32 w2c_chunky_xoroshirorandomworldgen_new_from_seed(w2c_chunky*, u32, u32);

/* export: 'xoroshirorandomworldgen_set_seed' */
void w2c_chunky_xoroshirorandomworldgen_set_seed(w2c_chunky*, u32, u32, u32);

/* export: 'xoroshirorandomworldgen_next_int' */
u32 w2c_chunky_xoroshirorandomworldgen_next_int(w2c_chunky*, u32, u32);

/* export: 'xoroshirorandomworldgen_next_long' */
void w2c_chunky_xoroshirorandomworldgen_next_long(w2c_chunky*, u32, u32);

/* export: 'xoroshirorandomworldgen_next_float' */
f32 w2c_chunky_xoroshirorandomworldgen_next_float(w2c_chunky*, u32);

/* export: 'xoroshirorandomworldgen_next_double' */
f64 w2c_chunky_xoroshirorandomworldgen_next_double(w2c_chunky*, u32);

/* export: 'xoroshirorandomworldgen_skip_next_n' */
void w2c_chunky_xoroshirorandomworldgen_skip_next_n(w2c_chunky*, u32, u32);

/* export: '__wbg_cavefinder_free' */
void w2c_chunky_0x5F_wbg_cavefinder_free(w2c_chunky*, u32);

/* export: 'cavefinder_new' */
u32 w2c_chunky_cavefinder_new(w2c_chunky*, u32);

/* export: 'cavefinder_find' */
u32 w2c_chunky_cavefinder_find(w2c_chunky*, u32, u32, u32, u32, u32);

/* export: '__wbg_xoroshirorandom_free' */
void w2c_chunky_0x5F_wbg_xoroshirorandom_free(w2c_chunky*, u32);

/* export: 'xoroshirorandom_new' */
u32 w2c_chunky_xoroshirorandom_new(w2c_chunky*, u32, u32, u32, u32);

/* export: 'xoroshirorandom_new_from_seed' */
u32 w2c_chunky_xoroshirorandom_new_from_seed(w2c_chunky*, u32, u32);

/* export: 'xoroshirorandom_set_seed' */
void w2c_chunky_xoroshirorandom_set_seed(w2c_chunky*, u32, u32, u32);

/* export: 'xoroshirorandom_next_int' */
u32 w2c_chunky_xoroshirorandom_next_int(w2c_chunky*, u32, u32);

/* export: 'xoroshirorandom_next_long' */
void w2c_chunky_xoroshirorandom_next_long(w2c_chunky*, u32, u32);

/* export: 'xoroshirorandom_next_float' */
f32 w2c_chunky_xoroshirorandom_next_float(w2c_chunky*, u32);

/* export: 'xoroshirorandom_next_double' */
f64 w2c_chunky_xoroshirorandom_next_double(w2c_chunky*, u32);

/* export: 'xoroshirorandom_skip_next_n' */
void w2c_chunky_xoroshirorandom_skip_next_n(w2c_chunky*, u32, u32);

/* export: '__wbg_biomeproviderend_free' */
void w2c_chunky_0x5F_wbg_biomeproviderend_free(w2c_chunky*, u32);

/* export: 'biomeproviderend_new' */
u32 w2c_chunky_biomeproviderend_new(w2c_chunky*, u32);

/* export: 'biomeproviderend_get_height_value' */
f32 w2c_chunky_biomeproviderend_get_height_value(w2c_chunky*, u32, u32, u32, u32, u32);

/* export: 'biomeproviderend_get_chunk_biome' */
u32 w2c_chunky_biomeproviderend_get_chunk_biome(w2c_chunky*, u32, u32, u32);

/* export: 'biomeproviderend_get_noise_biome' */
u32 w2c_chunky_biomeproviderend_get_noise_biome(w2c_chunky*, u32, u32, u32);

/* export: 'biomeproviderend_get_chunk_area' */
void w2c_chunky_biomeproviderend_get_chunk_area(w2c_chunky*, u32, u32, u32, u32, u32, u32);

/* export: '__wbg_biomeprovidernether_free' */
void w2c_chunky_0x5F_wbg_biomeprovidernether_free(w2c_chunky*, u32);

/* export: 'biomeprovidernether_new' */
u32 w2c_chunky_biomeprovidernether_new(w2c_chunky*, u32);

/* export: 'biomeprovidernether_get_noise_biome' */
u32 w2c_chunky_biomeprovidernether_get_noise_biome(w2c_chunky*, u32, u32, u32);

/* export: 'biomeprovidernether_get_chunk_biome' */
u32 w2c_chunky_biomeprovidernether_get_chunk_biome(w2c_chunky*, u32, u32, u32);

/* export: 'biomeprovidernether_get_chunk_area' */
void w2c_chunky_biomeprovidernether_get_chunk_area(w2c_chunky*, u32, u32, u32, u32, u32, u32);

/* export: '__wbindgen_add_to_stack_pointer' */
u32 w2c_chunky_0x5F_wbindgen_add_to_stack_pointer(w2c_chunky*, u32);

/* export: '__wbindgen_free' */
void w2c_chunky_0x5F_wbindgen_free(w2c_chunky*, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* CHUNKY_H_GENERATED_ */
