import { getAreaResult } from "./locator.js";

getAreaResult(
  "1675696067",
  [0, 0],
  [
    // "buriedTreasure",
    // "dungeon",
    // "netherFortress",
    // "bastionRemnant",
    // "endCity",
    // "slimeChunk",
    // "stronghold",
    // "village",
    // "mineshaft",
    // "woodlandMansion",
    // "pillagerOutpost",
    // "oceanRuin",
    // "oceanMonument",
    // "shipwreck",
    // "desertTemple",
    // "jungleTemple",
    //"witchHut",
    //"igloo",
    // "ruinedPortalOverworld",
    // "ruinedPortalNether",
    // "spawn",
    // "fossil",
    // "ravine",
    // "endGateway",
    // "amethystGeode",
    "ancientCity",
    // "itemOverworld",
    // "oreVein",
    // "cave",
    // "desertWell",
    // "trailRuin",
  ],
  {

  },
).then(console.log);
